class M12
{
	public static void main(String[] args) 
	{
		System.out.println("main begin");
		catch(ArithmeticException ex)
		{
		
		}
	
		System.out.println("main end");
	}
}
/*
we can not use catch alone
M12.java:6: error: 'catch' without 'try'
                catch(ArithmeticException ex)
                ^
1 error

*/